### ISSUE TITLE
range panic

### ISSUE THREAD

**Issue by mschnell1** [TechnikTobi/little_exif#25]
I already did have this with these images and it dies pers8ist with 0.5.1: 
using `new_from,_vec` and `write_top_vec` I add an "ImageDescription" tag to a file that did not feature this tag and save to a new file. 
The I) read the new file with the same program and get 
```
thread 'main' panicked at C:\Users\mschnell\.cargo\registry\src\index.crates.io-6f17d22bba15001f\little_exif-0.5.1\src\metadata.rs:566:70:
range end index 730 out of range for slice of length 728
```
I do `count = meta.data().len();`both before and after `set_tag` and `write_to_vec` and get 40 in both cases even though  "ImageDescription" was added (not overwritten). 

the files are: 
source: www.bitvibe.de/Upload/A0579322.jpg
destination: www.bitvibe.de/Upload/x.jpg

**Comment by mschnell1** [comment]
Waiting eagerly to  0.6.0 being accessible :)

**Comment by TechnikTobi** [comment]
Now available as `0.6.0-beta.1`

**Comment by mschnell1** [comment]
GREAT !
...testing

**Comment by mschnell1** [comment]
Ooops ?!?!?
```
        let tag_count_old = metadata.data().len();
|                                    ^^^^ method not found in `Metadata`
```
Seems to need to be accessed in a new way ?!?!?

**Comment by TechnikTobi** [comment]
Short story: The `.data()` function has been replaced as it does not make any sense anymore. Use `metadata.into_iter().count()` instead.

Long story: The `.data()` function has been replaced by using an iterator instead to simply access to the tags. The reason behind this is due to the structure of the data: The metadata in a JPEG, PNG, ... is basically an embedded TIFF, which in turn is made up of multiple *image file directories* (IFD). Each IFD stores one or more tags and possibly links to other IFDs. This structure of multiple IFDs that are possibly nested (resulting in *SubIFDs*) can't be captured by a single vector of tags. And, instead of making the user traverse each IFD and of each IFD the tags that are embedded and possibly having to deal with SubIFDs I decided to provide an iterator that simply traverses all of the IFDs and their tags. 

Hope that clears that up.

**Comment by mschnell1** [comment]
@TechnikTobi 
I did a first test with 0.6.0-betata.1, modifying my code in a way I guessed might be sensible (replacing `data() `by `into_iter()` ). 

Now the file (that had been written by little_exif v0.5.1) is scanned correctly !

Thanks !

**Comment by mschnell1** [comment]
Ah !
I did exactly what you suggested :) 

I also simply added a `next()` to the result of `get_tag()`.

How is this done correctly

**Comment by mschnell1** [comment]
> Long story: 

This EXIF stuff is really complex and rather weird. 

Thanks you for taking this up ! I really appreciate your work !

**Comment by TechnikTobi** [comment]
Using `.next()` on `get_tag()` is also new. The reason for this is that underneath this is also an iterator as a TIFF may consist of multiple IFDs, each one storing a version of a specific tag. Think of multi page TIFFs, with each image in the TIFF having its own image description. 

Previously I mainly focused on IFD0 (the first IFD), however, this may result in errors regarding the links to other (Sub)IFDs.

**Comment by TechnikTobi** [comment]
> This EXIF stuff is really complex and rather weird.

Absolutely. The way this is done is really weird. There are the standards on the one side (TIFF and the EXIF specifications that build upon that), and the implementations of the manufacturers on the other side, which are definitely not a 100% match (see all the "wrong format" issues where one format is expected and another one present...). 

Having worked on this project for >2 years now, I'd have structured EXIF in a different way, but as with all legacy standards that have been established for multiple decades, this won't go away anytime soon... ;-)

**Comment by mschnell1** [comment]
> Having worked on this project for >2 years now, I'd have structured EXIF in a different way, but as with all legacy standards that have been established for multiple decades, this won't go away anytime soon... ;-)

Seemingly the huge `exif-tool` is the only well accepted non-propriety implementable out there. up to now :) :) :) )

**Comment by mschnell1** [comment]
I started my 1000 file test set....
At some point I get: 
``
917: copying //marianne-1/public/hdd_1_1_1/Fotos/002/00249 Bonn 05/DSC72343.JPG -> t:/test/9170_DSC72343.JPG Fidelity, Bonn-Hardtberg, Juli 2005
thread 'main' panicked at C:\Users\Michael Schnell\.cargo\registry\src\index.crates.io-6f17d22bba15001f\little_exif-0.6.0-beta.1\src\ifd\mod.rs:263:21:
assertion `left == right` failed
  left: Some(1313426255)
 right: None
```
I'll upload the file ASAP.

I do get lots of messages from Little_Exif that it did not recognize the Exif information due to several reasons.

That is not harmful for my project, as in the end I only need what Little_Exif writes. the "old" tags will be ignored by the next step . 
I'll take a look if that does wok ASAP...

Moreover I'll report the issues with the files mentioned. ASAP

**Comment by TechnikTobi** [comment]
> Moreover I'll report the issues with the files mentioned. ASAP

Thanks, but please do so in a new issue.

**Comment by mschnell1** [comment]
> You can do that and simply check that calling `next()` a second time returns `None`, 

That is obvious.
My question was if (in what cases) it is possible that the next `next()` will return a `Some`, and what exactly that means.

**Comment by TechnikTobi** [comment]
>  My question was if (in what cases) it is possible that the next `next()` will return a `Some`, and what exactly that means.

`Some(ExifTag)` is returned with the first such tag that matches what you are looking for and that can be found in the order of the IFDs. It means that the tag exists in the file at some point. If e.g. multiple versions are present because of a multi-page TIFF, the tags are returned in the order of the pages.

**Comment by mschnell1** [comment]
I see
